### ISSUE TITLE
README Issues

### ISSUE THREAD

**Issue by aspiringVegetarian** [PalmerTurley34/fourier-transforms#1]
I think the first sentence below the screenshot should be updated from:

   A visualization **to** for sinusoid wave forms and fourier transforms.

to: 

   A visualization **tool** for sinusoid wave forms and fourier transforms.

Or, instead of "tool", maybe it should be "gui" to match the sentence above the screenshot.

Also, I think the superscript for the footnotes should go at the end of the word (or perhaps the end of the sentence), instead of at the front of the word.

Awesome project, thanks for sharing!

**Comment by PalmerTurley34** [comment]
Thanks for the feedback! Glad you liked it!
